Fix last 'line' in sample; prevents open quotes. (#1495)
The last line of the sample var may be an incomplete line. This causes the 'head' value to throw a CParserError:

> CParserError: Error tokenizing data. C error: EOF inside string starting at line 821

This occurs because of a hanging quote in a line due to the incompleteness. This patch will prevent the error during the head assignment.