Set rpc status while deleting (#823)
We're getting the following error, showing that rpc.active decreases
below zero.  This change is just a blind guess as to the cause.

    File "C:\projects\distributed\distributed\utils_test.py", line 326, in     check_active_rpc
      assert rpc.active == rpc_active
    AssertionError: assert -1 == 0