Quickfix missing import fastpaquet in _write_metadata func
Fixes AttributeError: 'bool' object has no attribute 'writer' when running df.to_parquet('dask_dataframe.parquet').